---
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: mnist-classifier
  namespace: seldon-model
spec:
  annotations:
    project_name: kubeflow-seldon
    deployment_version: v1
  name: mnist-classifier
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: hoangph3/tf_mnist_serving:v0.0.1
          name: tf-model
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: "/models"
            name: persistent-storage
        - image: hoangph3/sk_mnist_serving:v0.0.1
          name: sk-model
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: "/models"
            name: persistent-storage
        - image: hoangph3/mab_epsilon_greedy:1.5.0
          name: eg-router
          imagePullPolicy: IfNotPresent
        volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: nfs-1
    name: mnist-classifier
    replicas: 1
    graph:
      children:
      - name: sk-model
        type: MODEL
      - name: tf-model
        type: MODEL
      name: eg-router
      parameters:
      - name: n_branches
        value: '2'
        type: INT
      - name: epsilon
        value: '0.2'
        type: FLOAT
      - name: verbose
        value: '1'
        type: BOOL
      type: ROUTER
    svcOrchSpec:
      env: 
      - name: SELDON_ENABLE_ROUTING_INJECTION
        value: 'true'