version: '3'

services:
  feast_redis:
    image: redis:7.0.4
    container_name: feast_redis
    ports:
      - "6379:6379"
    networks:
      - feast-net

  feast_registry:
    container_name: feast_registry
    image: postgres:14.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=feast
    ports:
      - "5432:5432"
    # volumes: 
      # - ./feast-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    networks:
      - feast-net

networks:
  feast-net:
    name: feast-net
    driver: bridge
