apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: mnist-classifier
  namespace: seldon-model
spec:
  annotations:
    deployment_version: v1
    project_name: MNIST Example
  name: mnist-classifier
  predictors:
  - annotations:
      predictor_version: v1
    componentSpecs:
    - spec:
        containers:
        - image: hoangph3/tf_mnist_serving:v0.0.1
          imagePullPolicy: IfNotPresent
          name: tf-model
          volumeMounts:
          - mountPath: "/models"
            name: persistent-storage
        terminationGracePeriodSeconds: 1
        volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: nfs-1
    graph:
      children: []
      endpoint:
        type: REST
      name: tf-model
      type: MODEL
    name: mnist-classifier
    replicas: 1
