apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: "sk-mnist"
  labels:
    app: "seldon"
  namespace: seldon-model
spec:
  name: "sk-mnist"
  annotations:
    deployment_version: "v1"
    project_name: "MNIST Example"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: "sk-mnist"
          image: hoangph3/sk_mnist_serving:v0.0.1
          volumeMounts:
          - mountPath: "/models"
            name: "persistent-storage"
        terminationGracePeriodSeconds: 1

        volumes:
        - name: "persistent-storage"
          persistentVolumeClaim:
            claimName: "nfs-1"

    graph:
      children: []
      endpoint:
        type: "REST"
      name: "sk-mnist"
      type: "MODEL"
    name: "sk-mnist"
    replicas: 1
