apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: multi-worker
spec:
  tfReplicaSpecs:
    Worker:
      replicas: 3
      template:
        spec:
          containers:
            - name: tf-distributed-train
              image: hoangph3/mnist-distributed-training:v0.0.1
              imagePullPolicy: IfNotPresent
              args:
                - --epochs=100
                - --steps_per_epoch=100
                - --per_worker_batch=64
                - --saved_model_path=/models/saved_model_dir
                - --checkpoint_path=/models/checkpoints
              volumeMounts:
              - name: saved-model-dir
                mountPath: /models/saved_model_dir
              - name: checkpoints
                mountPath: /models/checkpoints
              - name: data-dir
                mountPath: /data/mnist
          volumes:
          - name: saved-model-dir
            hostPath: 
              path: /home/hoang/Downloads/mnist/saved_model_dir
          - name: checkpoints
            hostPath: 
              path: /home/hoang/Downloads/mnist/checkpoints
          - name: data-dir
            hostPath:
              path: /home/hoang/Downloads/mnist/data
