version: "3.2"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentiment_analysis
    image: hoangph3/sentiment-analysis:0.0.1
    ports:
      - '5000:5000'
      - '9000:9000'
