version: '3.0'

services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    container_name: zookeeper
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
    networks:
      - default
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.0.5:9092 #,PLAINTEXT_HOST://127.0.0.1:9092
      - KAFKA_CFG_LOG_RETENTION_HOURS=1
      - KAFKA_CFG_LOG_RETENTION_BYTES=30000000000
      - KAFKA_CFG_NUM_PARTITIONS=1
      #- KAFKA_LISTENERS:LISTENER_BOB://kafka:9092,LISTENER_FRED://localhost:9092
      #- KAFKA_ADVERTISED_LISTENERS:LISTENER_BOB://kafka:9092,LISTENER_FRED://localhost:9092
      #- KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
      #- KAFKA_INTER_BROKER_LISTENER_NAME:LISTENER_BOB
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
