apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: "mnist-kafka"
  namespace: seldon-model
spec:
  serverType: kafka
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: "classifier"
          image: hoangph3/sklearn_mnist_classifier:v0.0.1
    svcOrchSpec:
      env:
      - name: KAFKA_BROKER
        value: 10.105.143.149:9092
      - name: KAFKA_INPUT_TOPIC
        value: mnist-rest-input
      - name: KAFKA_OUTPUT_TOPIC
        value: mnist-rest-output
    graph:
      name: "classifier"
      type: "MODEL"
    name: "default"
    replicas: 1
