version: '3'

services:
  feast_redis:
    image: redis:7.0.4
    container_name: feast_redis
    ports:
      - "6379:6379"
    networks:
      - feast-net

  feast_push_server:
    image: feast-push-server
    container_name: feast_push_server
    build:
      context: .
      dockerfile: feature_repo/Dockerfile
    depends_on:
      feast_feature_server:
        condition: service_healthy
      feast_registry:
        condition: service_healthy
    ports:
      - "6567:6566"
    networks:
      - feast-net

  feast_feature_server:
    image: feast-feature-server
    container_name: feast_feature_server
    build:
      context: .
      dockerfile: feature_repo/Dockerfile
    depends_on:
      feast_registry:
        condition: service_healthy
    ports:
      - "6566:6566"
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:6566/health}"
      interval: "5s"
      retries: 5
    networks:
      - feast-net

  feast_registry:
    container_name: feast_registry
    image: postgres:14.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=feast
    ports:
      - "5432:5432"
    volumes: 
      - ./feast-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    networks:
      - feast-net

networks:
  feast-net:
    name: feast-net
    driver: bridge
