---
# Source: seldon-core-operator/templates/clusterrolebinding_seldon-manager-sas-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: seldon
    app.kubernetes.io/instance: 'release-name'
    app.kubernetes.io/name: 'seldon-core-operator'
    app.kubernetes.io/version: '1.14.0'
  name: seldon-manager-sas-rolebinding-seldon-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: seldon-manager-sas-role-seldon-system
subjects:
- kind: ServiceAccount
  name: seldon-manager
  namespace: 'seldon-system'
