---
# Source: seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: seldon
    app.kubernetes.io/instance: 'release-name'
    app.kubernetes.io/name: 'seldon-core-operator'
    app.kubernetes.io/version: '1.14.0'
    control-plane: seldon-controller-manager
  name: seldon-controller-manager
  namespace: 'seldon-system'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seldon
      app.kubernetes.io/instance: seldon1
      app.kubernetes.io/name: seldon
      app.kubernetes.io/version: v0.5
      control-plane: seldon-controller-manager
  template:
    metadata:
      annotations:
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
        sidecar.istio.io/inject: 'false'
      labels:
        app: seldon
        app.kubernetes.io/instance: seldon1
        app.kubernetes.io/name: seldon
        app.kubernetes.io/version: v0.5
        control-plane: seldon-controller-manager
    spec:
      containers:
      - args:
        - --enable-leader-election
        - --webhook-port=4443
        - --create-resources=$(MANAGER_CREATE_RESOURCES)
        - --log-level=$(MANAGER_LOG_LEVEL)
        - --leader-election-id=$(MANAGER_LEADER_ELECTION_ID)
        - ''
        command:
        - /manager
        env:
        - name: MANAGER_LEADER_ELECTION_ID
          value: 'a33bd623.machinelearning.seldon.io'
        - name: MANAGER_LOG_LEVEL
          value: 'INFO'
        - name: WATCH_NAMESPACE
          value: ''
        - name: RELATED_IMAGE_EXECUTOR
          value: ''
        - name: RELATED_IMAGE_STORAGE_INITIALIZER
          value: ''
        - name: RELATED_IMAGE_SKLEARNSERVER
          value: ''
        - name: RELATED_IMAGE_XGBOOSTSERVER
          value: ''
        - name: RELATED_IMAGE_MLFLOWSERVER
          value: ''
        - name: RELATED_IMAGE_TFPROXY
          value: ''
        - name: RELATED_IMAGE_TENSORFLOW
          value: ''
        - name: RELATED_IMAGE_EXPLAINER
          value: ''
        - name: RELATED_IMAGE_MOCK_CLASSIFIER
          value: ''
        - name: MANAGER_CREATE_RESOURCES
          value: 'false'
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONTROLLER_ID
          value: ''
        - name: AMBASSADOR_ENABLED
          value: 'true'
        - name: AMBASSADOR_SINGLE_NAMESPACE
          value: 'false'
        - name: PREDICTIVE_UNIT_HTTP_SERVICE_PORT
          value: '9000'
        - name: PREDICTIVE_UNIT_GRPC_SERVICE_PORT
          value: '9500'
        - name: PREDICTIVE_UNIT_DEFAULT_ENV_SECRET_REF_NAME
          value: ''
        - name: PREDICTIVE_UNIT_METRICS_PORT_NAME
          value: 'metrics'
        - name: ISTIO_ENABLED
          value: 'true'
        - name: KEDA_ENABLED
          value: 'false'
        - name: ISTIO_GATEWAY
          value: 'istio-system/seldon-gateway'
        - name: ISTIO_TLS_MODE
          value: ''
        - name: USE_EXECUTOR
          value: 'true'
        - name: EXECUTOR_CONTAINER_IMAGE_AND_VERSION
          value: 'docker.io/seldonio/seldon-core-executor:1.14.0'
        - name: EXECUTOR_CONTAINER_IMAGE_PULL_POLICY
          value: 'IfNotPresent'
        - name: EXECUTOR_PROMETHEUS_PATH
          value: '/prometheus'
        - name: EXECUTOR_SERVER_PORT
          value: '8000'
        - name: EXECUTOR_CONTAINER_USER
          value: '8888'
        - name: EXECUTOR_CONTAINER_SERVICE_ACCOUNT_NAME
          value: 'default'
        - name: EXECUTOR_SERVER_METRICS_PORT_NAME
          value: 'metrics'
        - name: EXECUTOR_REQUEST_LOGGER_DEFAULT_ENDPOINT
          value: 'http://default-broker'
        - name: EXECUTOR_REQUEST_LOGGER_WORK_QUEUE_SIZE
          value: '10000'
        - name: EXECUTOR_REQUEST_LOGGER_WRITE_TIMEOUT_MS
          value: '2000'
        - name: DEFAULT_USER_ID
          value: '8888'
        - name: EXECUTOR_DEFAULT_CPU_REQUEST
          value: '500m'
        - name: EXECUTOR_DEFAULT_MEMORY_REQUEST
          value: '512Mi'
        - name: EXECUTOR_DEFAULT_CPU_LIMIT
          value: '500m'
        - name: EXECUTOR_DEFAULT_MEMORY_LIMIT
          value: '512Mi'
        - name: DEPLOYMENT_NAME_AS_PREFIX
          value: 'false'
        - name: EXECUTOR_FULL_HEALTH_CHECKS
          value: 'false'
        image: 'docker.io/seldonio/seldon-core-operator:1.14.0'
        imagePullPolicy: 'IfNotPresent'
        name: manager
        ports:
        - containerPort: 4443
          name: webhook-server
          protocol: TCP
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: '500m'
            memory: '300Mi'
          requests:
            cpu: '100m'
            memory: '200Mi'
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      hostNetwork: false
      priorityClassName: ''
      securityContext:
        runAsUser: 8888
      serviceAccountName: 'seldon-manager'
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: seldon-webhook-server-cert
