---
# Source: seldon-core-operator/templates/rolebinding_seldon-leader-election-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: seldon
    app.kubernetes.io/instance: 'release-name'
    app.kubernetes.io/name: 'seldon-core-operator'
    app.kubernetes.io/version: '1.14.0'
  name: seldon-leader-election-rolebinding
  namespace: 'seldon-system'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: seldon-leader-election-role
subjects:
- kind: ServiceAccount
  name: 'seldon-manager'
  namespace: 'seldon-system'
