---
# Source: seldon-core-operator/templates/serviceaccount_seldon-manager.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: seldon
    app.kubernetes.io/instance: 'release-name'
    app.kubernetes.io/name: 'seldon-core-operator'
    app.kubernetes.io/version: '1.14.0'
  name: 'seldon-manager'
  namespace: 'seldon-system'
