---
# Source: seldon-core-operator/templates/service_seldon-webhook-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: seldon
    app.kubernetes.io/instance: 'release-name'
    app.kubernetes.io/name: 'seldon-core-operator'
    app.kubernetes.io/version: '1.14.0'
  name: seldon-webhook-service
  namespace: 'seldon-system'
spec:
  ports:
  - port: 443
    targetPort: 4443
  selector:
    app: seldon
    app.kubernetes.io/instance: seldon1
    app.kubernetes.io/name: seldon
    app.kubernetes.io/version: v0.5
    control-plane: seldon-controller-manager
